### ISSUE TITLE
keep chat session

### ISSUE THREAD

**Issue by francescor** [franalgaba/chatgpt-telegram-bot-serverless#13]
the chat has no memory, how to add a session identifier so to keep chat memory?

**Comment by franalgaba** [comment]
Hi @francescor . Yes, the chat has no memory as it would be needed to add the previous conversations to the prompt which increases the number of tokens per request thus increasing the cost of using the API. I'll look into adding an option for people who wants to have it.

Thank you for the feedback :)

**Comment by francescor** [comment]
> add the previous conversations to the prompt 

is this how it works? 
have a look at this one https://github.com/TheR1D/shell_gpt#chat  (it's python, too)

I've been using and it works perfectly: I just add a random string to keep the memory (but I am unable to check the code to see if the developer had to do what you wrote)

**Comment by franalgaba** [comment]
Yes, it is what he implemented. You can check it out [here](https://github.com/TheR1D/shell_gpt/blob/main/sgpt/cache.py#L64).

Nevertheless, the memory in the lambda would only work if it doesn't do a cold start.

**Comment by francescor** [comment]
oh, wow, I had no idea that's how should be done

thank you!
