### ISSUE TITLE
Cloudflare bot protection blocking requests

### ISSUE THREAD

**Issue by rwzc** [franalgaba/chatgpt-telegram-bot-serverless#6]
Checking if the site connection is secure
chat.openai.com needs to review the security of your connection before proceeding.

**Comment by rwzc** [comment]
See here https://github.com/acheong08/ChatGPT/issues/261

**Comment by franalgaba** [comment]
Hi @rwzc ! Thank you for raising the issue. I'll make the update as soon as possible :)
