### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by Ecupse** [franalgaba/chatgpt-telegram-bot-serverless#7]
Everything installed successfully but i get "There was an exception handling your message :(" when testing my telegram bot

**Comment by franalgaba** [comment]
Hi @Ecupse! The bot is at the moment not working until I find a workaround for the CloudFare restrictions from OpenAI. Sorry for the inconvenience.

**Comment by sbbbsbbb** [comment]
https://github.com/transitive-bullshit/chatgpt-api

**Comment by viszsec** [comment]
chatgpt api isnt avail as of today and the session based taking it out from browser wont work anymore. The repo needs to be updated.

**Comment by franalgaba** [comment]
Hi @viszsec @yanshibin ! The new version of the bot is now released using the new ChatGPT API :)
