### ISSUE TITLE
Private bot

### ISSUE THREAD

**Issue by serovar** [franalgaba/chatgpt-telegram-bot-serverless#8]
As it works now, the bot (using our personal API) is publicly accessible by everyone. I understand there is a way to make the bot respond only to the owner specifying that it has to answers only to his/her specific chat_id, but it is not possible to do it with BotFather and I can't find clear information on how to do it properly.

Could it be possible to add information on how to get this kind of "private" bot, to avoid having the world consume our credit?

**Comment by francescor** [comment]
absolutely agree, the setup you suggest is pretty dangerous, plus the cost of AWS (& no just OpenAI)

**Comment by franalgaba** [comment]
Hi @serovar . Thank you for the feedback, I understand your concern but I doubt anyone can figure out your public Lambda URL to consume your credits. Nevertheless, I'll look into it to see if it does not add much complexity and cost for not having the Lambda URL public.

Regarding the costs, the only risk is people consuming your OpenAI credits but they can't get nothing from it as it would be sent to your telegram. Regarding AWS I doubt your would surpass the AWS Free Tier:

> The AWS Lambda free tier includes one million free requests per month and 400,000 GB-seconds of compute time per month

Thank you.

**Comment by francescor** [comment]
Look at what happened to me yesterday:
* I setup everything (pretty smooth, thanks)
* then I went of my friend's phone and search in Telegram for my bot (it had chatpgt keywords in it, so kind of easy to spot mayne), anyhow as soon as I found the bot I could be able to use it in his phone.  Nothing appeared on my Telegram: the only warning are audio files saved in S3 which are not recorded by me.

note that

* Free tires are there as an incentive: anybody experienced will have an AWS account with no free tiers at all
* S3 costs too: at least suggest users to put a policy of the bucket to remove objects after 24 hours
